version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - share_network

  share-eat-it-elb:
    image: share-eat-it-elb:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: application-server-container
    restart: always
    ports:
      - "53597:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - share_network

networks:
  share_network:
    driver: bridge
